/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Practice02/scene.gltf --types -o src/pages/Public/Practice02/Model.tsx 
Author: bazooka (https://sketchfab.com/efrailustunbzk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3-axis-cnc-gantry-system-6ece6ea193b540bc9a50ad43315ecc9e
Title: 3-Axis CNC Gantry System
*/

import type * as THREE from 'three'
import type { ComponentProps } from 'react'
import { useGLTF, Html } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
}

interface ModelProps extends ComponentProps<'group'> {
  activePointIndex?: number
  showNumbers?: boolean
  onSelectPoint?: (index: number) => void
}

export function Model({
  activePointIndex = 0,
  showNumbers = true,
  onSelectPoint,
  ...props
}: ModelProps) {
  const { nodes } = useGLTF('/Practice02/scene.gltf') as unknown as GLTFResult

  // Hotspots defined in the exact GLTF mesh coordinate system matching user red circles
  const HOTSPOTS = [
    { id: 1, number: '1', pos: [90, -380, 780] as [number, number, number] }, // 1: Front motor box (Red Circle 1)
    { id: 2, number: '2', pos: [0, 180, 260] as [number, number, number] }, // 2: Crossbeam rail face (Red Circle 2)
    { id: 3, number: '3', pos: [-90, -200, 250] as [number, number, number] }, // 3: Left side rail (Red Circle 3)
    { id: 4, number: '4', pos: [90, 320, 700] as [number, number, number] }, // 4: Top spindle motor (Red Circle 4)
  ]

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[0, Math.PI / 2, 0]} scale={0.001}>
          {/* Main Structural Gantry Base - Dark Steel */}
          <mesh geometry={nodes.Object_3.geometry}>
            <meshStandardMaterial color="#1e293b" metalness={0.85} roughness={0.25} />
          </mesh>
          {/* Linear Precision Guide Rails - Polished Chrome */}
          <mesh geometry={nodes.Object_4.geometry}>
            <meshStandardMaterial color="#e2e8f0" metalness={0.95} roughness={0.1} />
          </mesh>
          {/* Carriage Blocks & Motor Mounts - Anodized Slate Aluminum */}
          <mesh geometry={nodes.Object_5.geometry}>
            <meshStandardMaterial color="#334155" metalness={0.8} roughness={0.3} />
          </mesh>
          {/* Drive & Spindle Components - Cyan Industrial Accent */}
          <mesh geometry={nodes.Object_6.geometry}>
            <meshStandardMaterial color="#0284c7" metalness={0.9} roughness={0.2} />
          </mesh>

          {/* Hotspot badges locked directly inside GLTF mesh transformation group */}
          {showNumbers &&
            HOTSPOTS.map((hs, idx) => {
              const isActive = activePointIndex === idx
              return (
                <Html key={hs.id} position={hs.pos} center scale={1000} zIndexRange={[100, 0]}>
                  <button
                    onClick={(e) => {
                      e.stopPropagation()
                      if (onSelectPoint) onSelectPoint(idx)
                    }}
                    className={`w-7 h-7 rounded-full font-mono flex items-center justify-center text-xs font-bold transition-all duration-300 shadow-xl cursor-pointer ${
                      isActive
                        ? 'bg-cyan-400 text-slate-950 scale-125 border-2 border-white shadow-cyan-400/80 ring-4 ring-cyan-400/30'
                        : 'bg-slate-950/90 text-white border border-slate-400/60 hover:scale-110 hover:border-cyan-400 hover:bg-slate-900'
                    }`}
                  >
                    {hs.number}
                  </button>
                </Html>
              )
            })}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Practice02/scene.gltf')
